# Generated by Django 4.2.16 on 2024-12-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0004_grade_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
    ]
